modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="unusualprehistory"
version="2.0.0"
displayName= "Unusual Prehistory"
logoFile= "logo.png"
itemIcon = "unusualprehistory:mesozoic_fossil"
configBackground = "unusualprehistory:textures/block/fire_opal_block.png"
credits= "Fred, Omatypaty, Crydigo, magmastrider, Nova, Reaper, IcyDwarf, The Indominator, Ghoul, Miceli, Chips, BrayDoesStuff, skyjay1#2076, Scouter456, Codyy, platypushasnohat, TheValiantSquidward"
authors= "Unusual Modding"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/unusual-prehistory"
description='''
A Mod that adds a variety of prehistoric creatures and a way to revive them!
'''

[[dependencies.unusualprehistory]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.unusualprehistory]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.geckolib]]
modId="geckolib"
mandatory=true
versionRange="[4.2,)"
ordering="BEFORE"
side="BOTH"